---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: all
  connection: local
  gather_facts: False

tasks:
  aci_tenant:
    tenant: ansible
    description: ansible tenant
    state: present
  delegate_to: localhost

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        state: "present"
        validate_certs: False
        description: "Tenant Created Using Ansible"
