---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: all
  connection: local
  gather_facts: False
  
 tasks:  
  - name: Query all tenants
    aci_tenant:
    state: query
    register: all_tenants
