---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: all
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "tenant"
      prompt: "What would you like to name your Tenant?"
      private: no

