---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: TASK 1 ENSURE uSeg Preferred_Group IS MODIFY
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "post"
        path: "api/node/mo/uni/tn-DevOps/ap-intranet/{{ item }}.json"
        content: {"fvAEPg":{"attributes":{"dn":"uni/tn-DevOps/ap-intranet/{{ item }}","isAttrBasedEPg":"true","prefGrMemb":"exclude"},"children":[]}}

      with_items:
        - epg-APP1_uSeg
        - epg-APP2_uSeg
        - epg-APP3_uSeg
        - epg-APP4_uSeg
        - epg-APP5_uSeg
...
