---
- name: USE ACI REST MODULE
  hosts: apic
  connection: local
  gather_facts: False
  
 
  tasks:
    - name: TASK 1 ENSURE uSeg IS CREATED
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        method: "post"
        path: "api/node/mo/uni/tn-DevOps/ap-intranet/{{ item }}.json"
        content: {"fvAEPg":{"attributes":{"dn":"uni/tn-DevOps/ap-intranet/{{ item }}".","isAttrBasedEPg":"true","name":"{{ item }}".","prefGrMemb":"include","pcEnfPref":"enforced","prio":"level3","rn":"{{ item }}".","status":"created"},"children":[{"fvCrtrn":{"attributes":{"dn":"uni/tn-DevOps/ap-intranet/{{ item }}/crtrn","name":"default","prec":"0","rn":"crtrn","status":"created,modified"},"children":[]}},{"fvRsCustQosPol":{"attributes":{"tnQosCustomPolName":"default","status":"created,modified"},"children":[]}},{"fvRsBd":{"attributes":{"tnFvBDName":"prod_bd","status":"created,modified"},"children":[]}},{"fvRsAEPgMonPol":{"attributes":{"tnMonEPGPolName":"default","status":"created,modified"},"children":[]}},{"fvRsDomAtt":{"attributes":{"tDn":"uni/vmmp-VMware/dom-TestVMM","resImedcy":"immediate","status":"created"},"children":[]}}]}}
      
      with_items: "{{ epg_uSeg }}"
